server:
   servlet:
      context-path: /firstmarket

spring:
   profiles:
      active:
         #- dev-mariadb
         - dev-h2
   jpa:
      show-sql: true

schedule:
   fixedRate:
      string: PT60S
---

spring:
   profiles: dev-h2
   h2:
      console:
         enabled: true

---

spring:
   profiles: dev-mariadb
   datasource:
      url: jdbc:mariadb://localhost:3306/fm?serverTimezone=UTC
      username: root
      password: misrra
      driver-class-name: org.mariadb.jdbc.Driver
      initialization-mode: always
      schema: classpath:sql/schema.sql
      data: classpath:sql/data.sql
   jpa:
      hibernate:
         ddl-auto: none