server:
   servlet:
      context-path: /firstmarket

spring:
   profiles:
      active:
         - dev-mariadb
         #- dev-h2
   #jpa:
      #show-sql: true

schedule:
   garbage-collection:
      cron: 0 15,30,45 * ? * *
      #fixed-rate-string: PT60S

validation:
   numeric:
      pages-min: 1
      pages-max: 5000
      stock-min: 0
      stock-max: 100000000
      image-max-size: 512000 # in bytes (500KB)
   regex:
      email: ^[_A-Za-z0-9-+]+(.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(.[A-Za-z0-9]+)*(.[A-Za-z]{2,})$
      password: ^(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,16}$ # The password must be at least 8 characters, with at least one lowercase, one uppercase and one number
      text-basic: ^[\s\w\-.,:"?¿¡!()äëïöüñáéíóúÄËÏÖÜÑÁÉÍÓÚ]{0,30}$
      text-long: ^[\s\w\-.,:;"?¿¡!()äëïöüñáéíóúÄËÏÖÜÑÁÉÍÓÚ]{0,1000}$
      text-query: ^[\s\w\-.,:"?¿¡!()äëïöüñáéíóúÄËÏÖÜÑÁÉÍÓÚ]{0,100}$
      isbn-code: ^(?:ISBN(?:-1[03])?:? )?(?=[0-9X]{10}$|(?=(?:[0-9]+[\- ]){3})[\- 0-9X]{13}$|97[89][0-9]{10}$|(?=(?:[0-9]+[\- ]){4})[\- 0-9]{17}$)(?:97[89][\- ]?)?[0-9]{1,5}[\- ]?[0-9]+[\- ]?[0-9]+[\- ]?[0-9X]$
      isbn-filter: '[\- ]|^ISBN(?:-1[03])?:?'
      image-mime-type: ^image\/.*$
      image-name: ^[ \w\-.]{1,30}$
      year: ^[\d]{1,4}$
      price: ^[\d]{0,9}([.][\d]{1,2})*$ # dependency with PriceIntervals enum, so keep an eye on it

security:
   lock:
      num-of-attempts: 2
      locking-minutes: 10
   token:
      expiration-in-minutes: 2
   random-password:
      num-of-lower-case: 2
      num-of-upper-case: 2
      num-of-digit: 2
      size: 10

front-end:
   search-criteria:
      num-of-authors: 4
      num-of-publishers: 5
      num-of-languages: 6

pagination:
   default-size:
      image: 5
      book-home: 20
      book-search: 15
   default-index: 0
---

spring:
   profiles: dev-h2
   h2:
      console:
         enabled: true

---

spring:
   profiles: dev-mariadb
   datasource:
      url: jdbc:mariadb://localhost:3306/fm?serverTimezone=UTC
      username: root
      password: misrra
      driver-class-name: org.mariadb.jdbc.Driver
      initialization-mode: always
      #schema: classpath:sql/schema.sql
      #data: classpath:sql/data.sql
   jpa:
      hibernate:
         ddl-auto: none