server:
   error:
      whitelabel:
         enabled: false

spring:
   profiles:
      active:
         - dev-postgresql  # comment @Lob on image.data
         #- dev-h2          # un-comment @Lob on image.data
   jpa:
      show-sql: false
   mail:
      host: smtp.gmail.com
      port: 587
      username: ${MAIL_ADDRESS:afirstmarket@gmail.com}
      password: ${MAIL_PW}
      properties:
         mail:
            smtp:
               auth: true
               starttls:
                  enable: true
               connectiontimeout: 5000
               timeout: 3000
               writetimeout: 5000

fm:
   host:
      address: ${HOST_ADDRESS:http://localhost:8080/}
   schedule:
      garbage-collection:
         cron: 0 */5 * ? * *
         #fixed-rate-string: PT60S
   payment:
      stripe:
         key:
            public: ${STRIPE_PUBLIC_KEY}
            private: ${STRIPE_SECRET_KEY}
            webhook: ${STRIPE_WEBHOOK_SECRET}
         pi-minutes: 15
         limit-of-naps: 2
         ips: 3.18.12.63,3.130.192.231,13.235.14.237,13.235.122.149,35.154.171.200,52.15.183.38,54.187.174.169,54.187.205.235,54.187.216.72,54.241.31.99,54.241.31.102,54.241.34.107
   validation:
      numeric:
         profile-min-year: 1900
         pages: 1,5000 # min,max
         stock: 0,100000000 # min,max
         image-max-size: 512000 # in bytes (512KB)
      regex:
         email: ^[_A-Za-z0-9-+]+(.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(.[A-Za-z0-9]+)*(.[A-Za-z]{2,})$
         password: ^(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,16}$ # The password must be at least 8 characters, with at least one lowercase, one uppercase and one number
         text-basic: ^[\s\w\-.,:"'?¿¡!()äëïöüñáéíóúÄËÏÖÜÑÁÉÍÓÚ]{0,150}$
         text-long: ^[\s\w\-.,:;"'?¿¡!()äëïöüñáéíóúÄËÏÖÜÑÁÉÍÓÚ]{0,1000}$
         text-query: ^[\s\w\-.,:"'?¿¡!()äëïöüñáéíóúÄËÏÖÜÑÁÉÍÓÚ]{0,100}$
         isbn-code: ^(?:ISBN(?:-1[03])?:? )?(?=[0-9X]{10}$|(?=(?:[0-9]+[\- ]){3})[\- 0-9X]{13}$|97[89][0-9]{10}$|(?=(?:[0-9]+[\- ]){4})[\- 0-9]{17}$)(?:97[89][\- ]?)?[0-9]{1,5}[\- ]?[0-9]+[\- ]?[0-9]+[\- ]?[0-9X]$
         isbn-filter: '[\- ]|^ISBN(?:-1[03])?:?'
         image-mime-type: ^image\/.*$
         image-name: ^[ \w\-.]{1,30}$
         year: ^[\d]{1,4}$
         price: ^[\d]{0,9}([.][\d]{1,2})*$ # dependency with PriceIntervals enum, so keep an eye on it
         phone: ^(\+)?(\([0-9]{0,4}\))?(([0-9\s.\-]){9,15})?$ # poor but enough approximation
   security:
      lock:
         num-of-attempts: 3
         locking-minutes: 10
      token:
         expiration-in-minutes: 15
      random-password:
         num-of-lower-case: 2
         num-of-upper-case: 2
         num-of-digit: 2
         size: 10
   front-end:
      common-components:
         snackbar: Book added to your cart
         num-of-main-categories: 10
         num-of-direct-main-categories: 6
      home:
         jum:
            title:
               text: 'FirstMarket'
               speed: 300
            subtitle:
               text: 'w h e r e . b o o k s . b e l o n g'
               speed: 30
         title-max-size: 30
         authors-max: 2
         trending-books-max: 15
         new-books-max: 15
      checkout:
         title-max-size: 20
      cart:
         title-max-size: 40
         authors-max: 2
      books:
         title-max-size: 60
         authors-max: 2
         stock-usage-warning-threshold: 50
         stock-warning-threshold: 5
         filter:
            general-max-size: 25
            author-part-max-size: 12
            num-of-authors: 8
            num-of-publishers: 8
            num-of-languages: 8
      orders:
         title-max-size: 60
   pagination:
      default-sort-index:
         book: 5
         image: 2
         user: 1
         order: 1
      default-size-index:
         image: 0
         home: 1
         search: 0
         user: 1
         order: 1
      default-index: 0

---

spring:
   profiles: dev-h2
   h2:
      console:
         enabled: true

---

spring:
   profiles: dev-postgresql
   datasource:
      url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/fm}
      username: ${JDBC_DATABASE_USERNAME:postgres}
      password: ${JDBC_DATABASE_PASSWORD}
      driver-class-name: org.postgresql.Driver
      initialization-mode: always
      schema: classpath:sql/schema.sql
      data: classpath:sql/data*.sql
   jpa:
      properties:
         hibernate:
            dialect : org.hibernate.dialect.PostgreSQLDialect
      hibernate:
         ddl-auto: none